using Document.Application.Abstractions;
using Microsoft.Extensions.Options;

namespace Document.Infrastructure.Storage;

/// <summary>
/// Local-disk implementation of IObjectStorage, used for development at zero cloud cost until
/// Azure Blob Storage is added as a second implementation of the same interface. Callers only
/// depend on IObjectStorage, so that swap needs no changes above the Infrastructure layer.
/// </summary>
public sealed class LocalFileStorage(IOptions<LocalFileStorageOptions> options) : IObjectStorage
{
    private readonly string _rootPath = Path.GetFullPath(options.Value.RootPath);

    public async Task SaveAsync(string key, Stream content, CancellationToken cancellationToken)
    {
        var fullPath = ResolvePath(key);

        var directory = Path.GetDirectoryName(fullPath);
        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        await using var fileStream = new FileStream(
            fullPath, FileMode.Create, FileAccess.Write, FileShare.None, bufferSize: 4096, useAsync: true);

        await content.CopyToAsync(fileStream, cancellationToken);
    }

    public Task<Stream> OpenReadAsync(string key, CancellationToken cancellationToken)
    {
        var fullPath = ResolvePath(key);

        Stream stream = new FileStream(
            fullPath, FileMode.Open, FileAccess.Read, FileShare.Read, bufferSize: 4096, useAsync: true);

        return Task.FromResult(stream);
    }

    public Task DeleteAsync(string key, CancellationToken cancellationToken)
    {
        File.Delete(ResolvePath(key));
        return Task.CompletedTask;
    }

    // Keys are GUID-based and generated by Application today, so this can never actually trigger -
    // but this method must stay safe regardless of what string a caller passes, since nothing
    // about IObjectStorage's contract prevents a future caller from doing otherwise.
    private string ResolvePath(string key)
    {
        var fullPath = Path.GetFullPath(Path.Combine(_rootPath, key));

        if (!fullPath.StartsWith(_rootPath, StringComparison.OrdinalIgnoreCase))
        {
            throw new ArgumentException(
                $"Storage key '{key}' resolves outside the configured storage root.", nameof(key));
        }

        return fullPath;
    }
}
